datasets:
  - c4_gec:
      name: reza-alipour/c4_200m_0.1percent
      type: gec
      info: GEC Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 2
      diff_mask: true
  - fce_gec:
      name: reza-alipour/fce
      type: gec
      info: GEC Dataset
      use: true
      repeat_with_different_prompts: 3
      mask_sample_size: 10
      diff_mask: true
  - lang8:
      name: reza-alipour/clang8
      type: gec
      info: GEC Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 1
      diff_mask: true
  - bea19:
      name: reza-alipour/bea19
      type: gec
      info: GEC Dataset
      use: true
      repeat_with_different_prompts: 2
      mask_sample_size: 10
      diff_mask: true
  - gyafc:
      name: reza-alipour/GYAFC-Train
      type: formality
      info: Formality Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 5
      diff_mask: false
  - disco_fuse:
      name: reza-alipour/discofuse_1percent
      type: coherence
      info: Coherence Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 4
      diff_mask: false
  - wiki_auto:
      name: reza-alipour/WikiAuto
      type: simplification
      info: Simplification Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 3
      diff_mask: false
  - wiki_large:
      name: reza-alipour/WikiLarge
      type: simplification
      info: Simplification Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 2
      diff_mask: false
  - para_bank_v2:
      name: reza-alipour/ParaBankV2
      type: paraphrase
      info: Paraphrasing Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 5
      diff_mask: false
  - wnc:
      name: reza-alipour/WNC
      type: neutralization
      info: Neutralization Dataset
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 5
      diff_mask: true
  - APPDIA_offensive:
      name: reza-alipour/APPDIA_offensive
      type: offensive
      info: Offensive Dataset ~ 2k
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 5
      diff_mask: true
  - Paradetox_toxic:
      name: reza-alipour/Paradetox_toxic
      type: toxic
      info: Toxic Dataset ~ 11k
      use: true
      repeat_with_different_prompts: 1
      mask_sample_size: 3
      diff_mask: true
  - IteraTeR_Simplicity:
      name: reza-alipour/IteraTeR_v2_fixed
      type: simplification
      info: Simplicity
      use: true
      repeat_with_different_prompts: 3
  - IteraTeR_Coherence:
      name: reza-alipour/IteraTeR_v2_fixed
      type: coherence
      info: Coherence
      use: true
      repeat_with_different_prompts: 4
  - IteraTeR_Fluency:
      name: reza-alipour/IteraTeR_v2_fixed
      type: gec
      info: GEC
      use: true
      repeat_with_different_prompts: 3
  - IteraTeR_V1_Simplicity:
      name: reza-alipour/IteraTer1
      type: simplification
      info: Simplicity
      use: true
      repeat_with_different_prompts: 3
  - IteraTeR_V1_Coherence:
      name: reza-alipour/IteraTer1
      type: coherence
      info: Coherence
      use: true
      repeat_with_different_prompts: 4
  - IteraTeR_V1_Fluency:
      name: reza-alipour/IteraTer1
      type: gec
      info: GEC
      use: true
      repeat_with_different_prompts: 3