gec_prompts:
  - Correct the following sentence for grammatical errors
  - Identify and fix any grammatical mistakes in the given text
  - Make the following sentence grammatically correct
  - Proofread and edit the following passage for grammar
  - Improve the grammar in the following text
  - Fix errors
  - Correct this
  - Grammar check
  - Edit for grammar
  - Proofread
  - Fix grammar
  - Fix grammar in this sentence
  - Fix grammar in the sentence
  - Fix grammar errors, Fix grammatical errors
  - Fix grammaticality, Fix all grammatical errors
  - Fix grammatical errors in this sentence
  - Fix grammar errors in this sentence
  - Fix grammatical mistakes in this sentence
  - Fix grammaticality in this sentence
  - Fix grammaticality of the sentence
  - Fix disfluencies in the sentence
  - Make the sentence grammatical
  - Make the sentence fluent
  - Fix errors in this text
  - Update to remove grammar errors
  - Remove all grammatical errors from this text
  - Improve the grammar of this text
  - Improve the grammaticality
  - Improve the grammaticality of this text
  - Improve the grammaticality of this sentence
  - Grammar improvements
  - Remove grammar mistakes
  - Remove grammatical mistakes
  - Fix the grammar mistakes
  - Fix grammatical mistakes
coherence_prompts:
  - Rewrite the following text to make it more coherent
  - Improve the coherence of this passage
  - Enhance the overall coherence of the following sentences
  - Make the transition between these sentences more seamless
  - Reorganize this paragraph to ensure better coherence
  - Smooth out the flow of ideas in this text
  - Create a more coherent narrative from these disjointed sentences
  - Enhance coherence
  - Improve flow
  - Refine coherence
  - Fix coherence
  - Fix coherence in this sentence
  - Fix coherence in the sentence
  - Fix coherence in this text
  - Fix coherence in the text
  - Fix coherence errors
  - Fix sentence flow
  - Fix sentence transition
  - Fix coherence errors in this sentence
  - Fix coherence mistakes in this sentence
  - Fix coherence in this sentence
  - Fix coherence of the sentence
  - Fix lack of coherence in the sentence
  - Make the text more coherent
  - Make the text coherent
  - Make the text more cohesive, logically linked and consistent as a whole
  - Make the text more cohesive
  - Improve the cohesiveness of the text
  - Make the text more logical
  - Make the text more consistent
  - Improve the consistency of the text
  - Make the text clearer
  - Improve the coherence of the text
simplification_prompts:
  - Simplify the following text
  - Make this text easier to understand
  - Provide a simplified version of the following passage
  - Clarify and simplify
  - Convert complex language into simpler terms
  - Create a simplified version of this content
  - Simplify
  - Clarify this
  - Make it simpler
  - Use plain language
  - Simplify the following
  - Clarify the sentence
  - Clarify this sentence
  - Clarify this text
  - Write a clearer version for the sentence
  - Write a clarified version of the sentence
  - Write a readable version of the sentence
  - Write a better readable version of the sentence
  - Rewrite the sentence more clearly
  - Rewrite this sentence clearly
  - Rewrite this sentence for clarity
  - Rewrite this sentence for readability
  - Improve this sentence for readability
  - Make this sentence better readable
  - Make this sentence more readable
  - Make this sentence readable
  - Make the sentence clear
  - Make the sentence clearer
  - Clarify
  - Make the text more understandable
  - Make this easier to read
  - Clarification
  - Change to clearer wording
  - Clarify this paragraph
  - Use clearer wording
  - Simplify the sentence
  - Simplify this sentence
  - Simplify this text
  - Write a simpler version for the sentence
  - Rewrite the sentence to be simpler
  - Rewrite this sentence in a simpler manner
  - Rewrite this sentence for simplicity
  - Rewrite this with simpler wording
  - Make the sentence simple
  - Make the sentence simpler
  - Make this text less complex
  - Make this simpler
  - Simplify
  - Simplification
  - Change to simpler wording
  - Simplify this paragraph
  - Simplify this text
  - Use simpler wording
  - Make this easier to understand
paraphrasing_prompts:
  - Paraphrase the following sentence
  - Provide an alternative wording for this text
  - Rewrite the following passage using different words
  - Offer a paraphrased version of this content
  - Create a different phrasing for the following text
  - Give me a reworded version of this sentence
  - Change the wording of this paragraph
  - Paraphrase
  - Reword this
  - Different phrasing
  - Provide an alternative
  - Change the wording
  - Paraphrase the sentence
  - Paraphrase this sentence
  - Paraphrase this text
  - Write a paraphrase for the sentence
  - Write a paraphrased version of the sentence
  - Rewrite the sentence with different wording
  - Use different wording
  - Rewrite this sentence
  - Reword this sentence
  - Rephrase this sentence
  - Rewrite this text
  - Reword this text
  - Rephrase this text
neutralization_prompts:
  - Neutralize the following text to make it more objective
  - Remove bias and make this statement neutral
  - Rewrite this passage to eliminate subjectivity
  - Make this text less opinionated and more neutral
  - Convert this content into a neutral and unbiased form
  - Create a neutral version of this text
  - Neutralize
  - Make it objective
  - Remove bias
  - Create a neutral version
  - Remove POV
  - Remove POVs
  - Remove POV in this text
  - Remove POVs in this text
  - Neutralize this text
  - Neutralize the text
  - Neutralize this sentence
  - Neutralize the sentence
  - Make this more neutral
  - Make this text more neutral
  - Make this sentence more neutral
  - Make this paragraph more neutral
  - Remove unsourced opinions
  - Remove unsourced opinions from this text
  - Remove non-neutral POVs
  - Remove non-neutral POV
  - Remove non-neutral points of view
  - Remove points of view, Make this text less bias
offensive_prompts:
  - Modify this text to make it less offensive
  - Rephrase the following content to be more respectful
  - Make the tone of this passage less offensive and more polite
  - Remove offensive language and replace it with more appropriate words
  - Make this statement less offensive and more constructive
  - Less offensive
  - Be more respectful
  - Remove offensive language
toxic_prompts:
  - Revise this text to make it less toxic
  - Eliminate harmful language and tone from the following content
  - Make the tone of this passage less toxic and more constructive
  - Remove toxic elements and replace them with more positive language
  - Make this statement less toxic and more respectful
  - Less toxic
  - Be more positive
  - Remove toxicity
formality_prompts:
  - Elevate the formality of the following text
  - Make this content sound more formal
  - Enhance the formal tone of this passage
  - Transform this text into a more formal style
  - Create a version of this content that is more dignified and formal
  - Add a formal touch to this statement
  - Increase the formality of this text
  - Formalize
  - Make it formal
  - Enhance formality
  - Create a formal version
  - Add a formal touch
  - Formalize
  - Improve formality
  - Formalize the sentence
  - Formalize this sentence
  - Formalize the text
  - Formalize this text
  - Make this formal
  - Make this more formal
  - Make this sound more formal
  - Make the sentence formal
  - Make the sentence more formal
  - Make the sentence sound more formal
  - Write more formally
  - Write less informally
  - Rewrite more formally
  - Write this more formally
  - Rewrite this more formally
  - Write in a formal manner
  - Write in a more formal manner
  - Rewrite in a more formal manner
formality_rev_prompts:
  - Make this content sound more casual
  - Tone down the formal tone of this passage
  - Transform this text into a more casual style
  - Add a casual touch to this statement
  - Decrease the formality of this text
  - Make it casual
  - Lessen formality
  - Create a casual version
  - Add a casual touch
do_not_edit_prompts:
  - Copy the following text as is
  - Do not make any changes, just replicate this text
  - Exact copy
  - Duplicate without alterations
  - Preserve the original text
  - Reproduce this text without editing
  - Keep the text unchanged
  - Copy
  - Replicate
  - No edits
  - Duplicate
  - Keep it as is